name: mantis_banner_ads
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.4 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  webview_flutter: 4.0.6 # check the latest version on pub.dev
  url_launcher: 6.1.10 # check the latest version on pub.dev

  cupertino_icons: ^1.0.2
  path_provider: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
